In [9]:
import numpy as np
import pandas as pd
import sqlalchemy
# from sqlalchemy.ext.automap import automap_base
# from sqlalchemy.orm import Session
from sqlalchemy import create_engine

from flask import Flask, jsonify, render_template, redirect

from config import sqlkey
#################################################
# Database Setup
#################################################

conn = create_engine(f'postgresql://postgres:{sqlkey}@localhost:5432/Money_Ball_DB').connect()

In [10]:
df = pd.read_csv('Data/Final_Data/MLB.csv')
df.to_json("MLB.json")

In [9]:

for row in pd.read_sql_query("SELECT * FROM nba", conn):
    print(test)

ValueError: too many values to unpack (expected 2)

In [17]:
jsonify([row for i,row in results.iterrows()])

RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.

In [29]:
results = pd.read_sql_query("SELECT * FROM champion_table", conn)

In [30]:
results

              city   mlb   nba   nfl   nhl  mls  total      lat       lng
0         New York  35.0   4.0   9.0   8.0  5.0   61.0  40.6943  -73.9249
1           Boston  10.0  17.0   6.0   7.0  0.0   40.0  42.3188  -71.0846
2          Chicago   6.0   6.0  11.0   6.0  3.0   32.0  41.8373  -87.6862
3      Los Angeles   7.0  12.0   2.0   3.0  7.0   31.0  34.1139 -118.4068
4         Montreal   0.0   0.0   0.0  26.0  0.0   26.0  46.4312  -90.2382
5          Detroit   4.0   3.0   4.0  11.0  0.0   22.0  42.3834  -83.1024
6   San Francisco    7.0   5.0   7.0   0.0  3.0   22.0  37.7562 -122.4430
7     Philadelphia   7.0   4.0   5.0   2.0  1.0   19.0  40.0077  -75.1339
8          Toronto   2.0   1.0   0.0  13.0  2.0   18.0  40.4581  -80.6096
9       Pittsburgh   5.0   1.0   6.0   5.0  0.0   17.0  40.4396  -79.9762
10       St. Louis  11.0   1.0   1.0   1.0  0.0   14.0  38.6358  -90.2451
11      Washington   2.0   1.0   5.0   1.0  4.0   13.0  38.9047  -77.0163
12       Green Bay   0.0   0.0  13.0   0.0  0.0   13.0  44.5150  -87.9896
13       Cleveland   2.0   1.0  10.0   0.0  0.0   13.0  41.4767  -81.6804
14       Baltimore   3.0   1.0   5.0   0.0  0.0    9.0  39.3051  -76.6144
15          Dallas   0.0   1.0   6.0   1.0  1.0    9.0  32.7936  -96.7662
16         Houston   1.0   2.0   2.0   2.0  2.0    9.0  29.7863  -95.3889
17     Minneapolis   2.0   5.0   0.0   0.0  0.0    7.0  44.9635  -93.2678
18     Kansas City   2.0   0.0   2.0   0.0  3.0    7.0  39.1239  -94.5541
19           Miami   2.0   3.0   2.0   0.0  0.0    7.0  25.7839  -80.2102
20          Denver   0.0   0.0   3.0   2.0  1.0    6.0  39.7621 -104.8759
21       Tampa Bay   0.0   0.0   2.0   2.0  2.0    6.0  27.9942  -82.4451
22     San Antonio   0.0   5.0   0.0   0.0  0.0    5.0  29.4658  -98.5253
23        Edmonton   0.0   0.0   0.0   5.0  0.0    5.0  36.9854  -85.6193
24      Cincinnati   5.0   0.0   0.0   0.0  0.0    5.0  39.1413  -84.5061
25         Seattle   0.0   1.0   1.0   1.0  2.0    5.0  47.6211 -122.3244
26    Indianapolis   0.0   3.0   1.0   0.0  0.0    4.0  39.7771  -86.1458
27          Ottawa   0.0   0.0   0.0   4.0  0.0    4.0  41.3532  -88.8306
28         Atlanta   1.0   0.0   0.0   0.0  2.0    3.0  33.7627  -84.4224
29          Newark   0.0   0.0   0.0   3.0  0.0    3.0  40.7245  -74.1725
30        Winnipeg   0.0   0.0   0.0   3.0  0.0    3.0  49.8951  -97.1384
31          Canton   0.0   0.0   2.0   0.0  0.0    2.0  40.8075  -81.3677
32        Columbus   0.0   0.0   0.0   0.0  2.0    2.0  39.9862  -82.9850
33       Milwaukee   1.0   1.0   0.0   0.0  0.0    2.0  43.0642  -87.9673
34        Portland   0.0   1.0   0.0   0.0  1.0    2.0  45.5372 -122.6500
35       Rochester   0.0   1.0   0.0   0.0  1.0    2.0  43.1680  -77.6162
36  Salt Lake City   0.0   1.0   0.0   0.0  1.0    2.0  40.7777 -111.9306
37         Buffalo   0.0   0.0   2.0   0.0  0.0    2.0  42.9016  -78.8487
38       Vancouver   0.0   0.0   0.0   1.0  1.0    2.0  45.6366 -122.5967
39           Akron   0.0   0.0   1.0   0.0  0.0    1.0  41.0798  -81.5219
40     New Orleans   0.0   0.0   1.0   0.0  0.0    1.0  30.0687  -89.9288
41         Phoenix   1.0   0.0   0.0   0.0  0.0    1.0  33.5722 -112.0891
42      Providence   0.0   0.0   1.0   0.0  0.0    1.0  41.8230  -71.4187
43         Raleigh   0.0   0.0   0.0   1.0  0.0    1.0  35.8325  -78.6435
44        Syracuse   0.0   1.0   0.0   0.0  0.0    1.0  43.0409  -76.1438
45           Tulsa   0.0   0.0   0.0   0.0  1.0    1.0  36.1284  -95.9042
46       San Diego   0.0   0.0   1.0   0.0  0.0    1.0  32.8312 -117.1225
47      Louisville   0.0   1.0   0.0   0.0  0.0    1.0  38.1663  -85.6485
48        Victoria   0.0   0.0   0.0   1.0  0.0    1.0  28.8285  -96.9850
49         Calgary   0.0   0.0   0.0   1.0  0.0    1.0  51.0447 -114.0719
50     Quebec City   0.0   0.0   0.0   1.0  0.0    1.0  46.8139  -71.2080

In [ ]:
results.to_dict()